# Scraping stuff in bulk

In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('08-classwork/restaurants.tsv', sep='\t')

In [6]:
df.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>categories</th>
      <th>name</th>
      <th>price</th>
      <th>rating</th>
      <th>url</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Italian</td>
      <td>La Piccola Cucina</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/la-piccola-cucina-new...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Italian</td>
      <td>Pisticci</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/pisticci-new-york?osq...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Italian</td>
      <td>Max Soha</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/max-soha-new-york?osq...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Italian</td>
      <td>Arco Cafe</td>
      <td>$$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/arco-cafe-new-york?os...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Pizza, Italian</td>
      <td>Mezzogiorno</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/mezzogiorno-new-york-...</td>
    </tr>
  </tbody>
</table>
</div>

## Functions

In [12]:
def get_price_range(yelp_range: str) -> str:
  replacement = {
    '$': 'cheap',
    '$$': 'normal',
    '$$$': 'expensive',
    '$$$$': 'insane'
  }

  return replacement[yelp_range]

In [14]:
df['price_range'] = df['price'].apply(get_price_range)
df.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>categories</th>
      <th>name</th>
      <th>price</th>
      <th>rating</th>
      <th>url</th>
      <th>price_range</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Italian</td>
      <td>La Piccola Cucina</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/la-piccola-cucina-new...</td>
      <td>normal</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Italian</td>
      <td>Pisticci</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/pisticci-new-york?osq...</td>
      <td>normal</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Italian</td>
      <td>Max Soha</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/max-soha-new-york?osq...</td>
      <td>normal</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Italian</td>
      <td>Arco Cafe</td>
      <td>$$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/arco-cafe-new-york?os...</td>
      <td>normal</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Pizza, Italian</td>
      <td>Mezzogiorno</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/mezzogiorno-new-york-...</td>
      <td>normal</td>
    </tr>
  </tbody>
</table>
</div>

In [15]:
def get_somas_opinion(restaurant):
  if restaurant['price'] == '$' and 'Seafood' not in restaurant['categories']:
    return 'love'
  else:
    return 'hate'

In [19]:
# in order to apply functions to the whole data frame based on its rows, 
# it needs to be run with 'axis=1'
df['somas_opinion'] = df.apply(get_somas_opinion, axis=1)

In [20]:
df.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>categories</th>
      <th>name</th>
      <th>price</th>
      <th>rating</th>
      <th>url</th>
      <th>price_range</th>
      <th>somas_opinion</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Italian</td>
      <td>La Piccola Cucina</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/la-piccola-cucina-new...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Italian</td>
      <td>Pisticci</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/pisticci-new-york?osq...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Italian</td>
      <td>Max Soha</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/max-soha-new-york?osq...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Italian</td>
      <td>Arco Cafe</td>
      <td>$$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/arco-cafe-new-york?os...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Pizza, Italian</td>
      <td>Mezzogiorno</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/mezzogiorno-new-york-...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
  </tbody>
</table>
</div>

## scrape stuff

In [ ]:
import requests
from bs4 import BeautifulSoup

In [45]:
def get_address_info(row):
  raw_data = requests.get(row['url']).content
  soup = BeautifulSoup(raw_data, 'html.parser')
  raw_address = soup.find(class_='street-address').get_text()
  address = raw_address.strip()
  zipcode = raw_address.strip().split(' ')[-1]
  print(address)
  print(zipcode)
  return pd.Series({
    'zipcode': zipcode,
    'address': address
  })

In [46]:
new_df = df.apply(get_address_info, axis=1).join(df)
new_df

964 Amsterdam AveNew York, NY 10025
10025

964 Amsterdam AveNew York, NY 10025
10025

125 La Salle StNew York, NY 10027
10027

1274 Amsterdam AveNew York, NY 10027
10027

886 Amsterdam AveNew York, NY 10025
10025

2791 BroadwayNew York, NY 10025
10025

1034 Amsterdam AveNew York, NY 10025
10025

53 W 106 StNew York, NY 10025
10025

1600 Amsterdam AveNew York, NY 10031
10031

3143 BroadwayNew York, NY 10027
10027

1415 Second AveNew York, NY 10021
10021

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>zipcode</th>
      <th>address</th>
      <th>categories</th>
      <th>name</th>
      <th>price</th>
      <th>rating</th>
      <th>url</th>
      <th>price_range</th>
      <th>somas_opinion</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>10025</td>
      <td>964 Amsterdam AveNew York, NY 10025</td>
      <td>Italian</td>
      <td>La Piccola Cucina</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/la-piccola-cucina-new...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>1</th>
      <td>10027</td>
      <td>125 La Salle StNew York, NY 10027</td>
      <td>Italian</td>
      <td>Pisticci</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/pisticci-new-york?osq...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>2</th>
      <td>10027</td>
      <td>1274 Amsterdam AveNew York, NY 10027</td>
      <td>Italian</td>
      <td>Max Soha</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/max-soha-new-york?osq...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>3</th>
      <td>10025</td>
      <td>886 Amsterdam AveNew York, NY 10025</td>
      <td>Italian</td>
      <td>Arco Cafe</td>
      <td>$$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/arco-cafe-new-york?os...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>4</th>
      <td>10025</td>
      <td>2791 BroadwayNew York, NY 10025</td>
      <td>Pizza, Italian</td>
      <td>Mezzogiorno</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/mezzogiorno-new-york-...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>5</th>
      <td>10025</td>
      <td>1034 Amsterdam AveNew York, NY 10025</td>
      <td>Italian</td>
      <td>Tartina</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/tartina-new-york-4?os...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>6</th>
      <td>10025</td>
      <td>53 W 106 StNew York, NY 10025</td>
      <td>Italian</td>
      <td>Osteria 106</td>
      <td>$$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/osteria-106-new-york?...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>7</th>
      <td>10031</td>
      <td>1600 Amsterdam AveNew York, NY 10031</td>
      <td>Pizza, Italian, Bars</td>
      <td>Fumo Pizza-Bar-Pasta</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/fumo-pizza-bar-pasta-...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>8</th>
      <td>10027</td>
      <td>3143 BroadwayNew York, NY 10027</td>
      <td>Pizza, Italian</td>
      <td>Bettolona</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/bettolona-new-york?os...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10021</td>
      <td>1415 Second AveNew York, NY 10021</td>
      <td>Italian, Pasta Shops</td>
      <td>Bigoi Venezia</td>
      <td>$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/bigoi-venezia-new-yor...</td>
      <td>cheap</td>
      <td>love</td>
    </tr>
  </tbody>
</table>
</div>

In [47]:
new_df.to_csv('08-classwork/restaurants-with-zip.tsv', sep='\t', index=False)

## Trying to scrape with a single row

In [48]:
name = 'Burger & Lobster'
zipcode = '10011'
url = 'http://a816-restaurantinspection.nyc.gov/RestaurantInspection/SearchBrowse.do'

In [56]:
import time

driver = webdriver.Firefox()

In [63]:
def get_inspection_results(row):
  try:
    driver.get(
      'http://a816-restaurantinspection.nyc.gov/RestaurantInspection/SearchBrowse.do')
    restaurant_input = driver.find_element_by_id('searchByNameText')
    zip_input = driver.find_element_by_id('searchByZipCodeText')

    restaurant_input.send_keys(row['name'])
    zip_input.send_keys(row['zipcode'])
    # wait for 1 second
    time.sleep(1)

    button = driver.find_element_by_name('button_display')
    button.click()
    time.sleep(1)
    driver.find_element_by_class_name('resultCell').find_element_by_tag_name(
      'a').click()

    time.sleep(1)
    violationScore = driver.find_element_by_css_selector(
      '#violationScore b').text
    violationDescriptions = driver.find_element_by_css_selector(
      '#violationDesc').text
    return pd.Series({
      'points': violationScore,
      'violations': violationDescriptions
    })
  except:
    return pd.Series({})

In [58]:
violationDescriptions

'Sanitary Violations\n1) Cold food item held above 41º F (smoked fish and reduced oxygen packaged foods above 38 ºF) except during necessary preparation.\n2) Thawing procedures improper.\n3) Non-food contact surface improperly constructed. Unacceptable material used. Non-food contact surface or equipment improperly maintained and/or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.'

In [59]:
violationScore

'12'

In [64]:
violations_df = new_df.apply(get_inspection_results, axis=1).join(
  new_df)

violations_df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>points</th>
      <th>violations</th>
      <th>zipcode</th>
      <th>address</th>
      <th>categories</th>
      <th>name</th>
      <th>price</th>
      <th>rating</th>
      <th>url</th>
      <th>price_range</th>
      <th>somas_opinion</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>7</td>
      <td>Sanitary Violations\n1) Wiping cloths soiled o...</td>
      <td>10025</td>
      <td>964 Amsterdam AveNew York, NY 10025</td>
      <td>Italian</td>
      <td>La Piccola Cucina</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/la-piccola-cucina-new...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>1</th>
      <td>8</td>
      <td>Sanitary Violations\n1) Wiping cloths soiled o...</td>
      <td>10027</td>
      <td>125 La Salle StNew York, NY 10027</td>
      <td>Italian</td>
      <td>Pisticci</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/pisticci-new-york?osq...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>2</th>
      <td>12</td>
      <td>Sanitary Violations\n1) Live roaches present i...</td>
      <td>10027</td>
      <td>1274 Amsterdam AveNew York, NY 10027</td>
      <td>Italian</td>
      <td>Max Soha</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/max-soha-new-york?osq...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>3</th>
      <td>12</td>
      <td>Sanitary Violations\n1) Cold food item held ab...</td>
      <td>10025</td>
      <td>886 Amsterdam AveNew York, NY 10025</td>
      <td>Italian</td>
      <td>Arco Cafe</td>
      <td>$$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/arco-cafe-new-york?os...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>4</th>
      <td>7</td>
      <td>Sanitary Violations\n1) Food not protected fro...</td>
      <td>10025</td>
      <td>2791 BroadwayNew York, NY 10025</td>
      <td>Pizza, Italian</td>
      <td>Mezzogiorno</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/mezzogiorno-new-york-...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>5</th>
      <td>3</td>
      <td>Sanitary Violations\n1) Food contact surface n...</td>
      <td>10025</td>
      <td>1034 Amsterdam AveNew York, NY 10025</td>
      <td>Italian</td>
      <td>Tartina</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/tartina-new-york-4?os...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>6</th>
      <td>28</td>
      <td>Sanitary Violations\n1) Evidence of mice or li...</td>
      <td>10025</td>
      <td>53 W 106 StNew York, NY 10025</td>
      <td>Italian</td>
      <td>Osteria 106</td>
      <td>$$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/osteria-106-new-york?...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>7</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>10031</td>
      <td>1600 Amsterdam AveNew York, NY 10031</td>
      <td>Pizza, Italian, Bars</td>
      <td>Fumo Pizza-Bar-Pasta</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/fumo-pizza-bar-pasta-...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>8</th>
      <td>12</td>
      <td>Sanitary Violations\n1) Food not cooled by an ...</td>
      <td>10027</td>
      <td>3143 BroadwayNew York, NY 10027</td>
      <td>Pizza, Italian</td>
      <td>Bettolona</td>
      <td>$$</td>
      <td>4.0</td>
      <td>https://www.yelp.com/biz/bettolona-new-york?os...</td>
      <td>normal</td>
      <td>hate</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2</td>
      <td>Sanitary Violations\n1) Mechanical or natural ...</td>
      <td>10021</td>
      <td>1415 Second AveNew York, NY 10021</td>
      <td>Italian, Pasta Shops</td>
      <td>Bigoi Venezia</td>
      <td>$</td>
      <td>4.5</td>
      <td>https://www.yelp.com/biz/bigoi-venezia-new-yor...</td>
      <td>cheap</td>
      <td>love</td>
    </tr>
  </tbody>
</table>
</div>

In [65]:
violations_df.to_csv('08-classwork/restaurants-with-violations.tsv',
                     sep='\t', index=False)